name: ublox-gnss-demo


on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build and push amd64
        run: |
          ./build.sh
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  build-and-push-arm64:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build and push arm64
        run: |
          ./build.sh --platform linux/arm64
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64